FROM python:3.8

ENV C_FORCE_ROOT="true"
ENV CELERY_BROKER_URL="redis://redis:6379/0"
ENV CELERY_RESULT_BACKEND="redis://redis:6379/0"

WORKDIR /app
ADD . /app
RUN pip install -r requirements.txt
CMD ["celery", "-A", "fileuploader", "worker", "--loglevel=info"]